name: actions

on: [push, pull_request]

env:
  EXECUTABLES: "raytracer"

jobs:
  check_program_compilation:
    name: "check that the program compiles correctly"
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v4
      - run: make
        timeout-minutes: 2
      - run: make clean
      - run: |
          for executable in $EXECUTABLES; do
            if [ ! -x "$executable" ]; then
              echo "Executable $executable is missing or not executable"
              exit 1
            fi
          done
